services:
  # Web Service
  - type: web
    name: gemini-chat-app
    runtime: python
    region: singapore  # Worker と同じリージョン、Redis 再作成時に同じリージョンで
    plan: free  # または starter, standard など
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn -c gunicorn.conf.py wsgi:app"
    envVars:
      # Python version
      - key: PYTHON_VERSION
        value: 3.12.1

      # Flask settings
      - key: SECRET_KEY
        generateValue: true  # Renderが自動生成

      - key: FORCE_HTTPS
        value: true

      - key: SESSION_COOKIE_SECURE
        value: true

      - key: SESSION_COOKIE_HTTPONLY
        value: true

      - key: SESSION_COOKIE_SAMESITE
        value: Lax

      # Gemini API (これらは手動で設定してください)
      - key: GEMINI_API_KEY
        sync: false  # 手動設定が必要

      - key: GOOGLE_API_VERSION
        value: v1beta

      - key: DEFAULT_GEMINI_MODEL
        value: gemini-2.5-flash

      - key: FALLBACK_GEMINI_MODEL
        value: gemini-2.5-pro

      - key: USE_MOCK_GEMINI
        value: false

      # Search API (これらは手動で設定してください)
      - key: SEARCH_PROVIDER
        value: google_cse

      - key: GOOGLE_API_KEY
        sync: false  # 手動設定が必要

      - key: GOOGLE_CSE_ID
        sync: false  # 手動設定が必要

      # Gunicorn
      - key: WEB_CONCURRENCY
        value: 2

      # Database (PostgreSQL接続は自動設定)
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-chat-db
          property: connectionString

      # Redis (Redis接続は自動設定)
      - key: REDIS_URL
        fromService:
          type: redis
          name: gemini-chat-redis
          property: internalConnectionString

  # PostgreSQL Database
  - type: pserv
    name: gemini-chat-db
    region: singapore  # Web/Worker Service と同じリージョン
    plan: free  # または starter
    ipAllowList: []  # 空 = すべてのIPを許可

  # RQ Worker (Deep Research background processing)
  # Note: Render Free plan does not support background_worker type
  # Using web service instead (httpPort will be ignored)
  - type: web
    name: gemini-chat-worker
    runtime: python
    region: singapore  # Web Service, PostgreSQL, Redis と同じリージョン
    plan: free
    buildCommand: "bash ./build.sh"
    startCommand: "python run_worker.py"
    autoDeployOnPush: false  # 手動デプロイのみ（Webサービスではないため）
    envVars:
      # Python version
      - key: PYTHON_VERSION
        value: 3.12.1

      # Secret key (auto-generate for Worker service)
      - key: SECRET_KEY
        generateValue: true

      # Database (PostgreSQL接続は自動設定)
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-chat-db
          property: connectionString

      # Redis (Redis接続は自動設定)
      - key: REDIS_URL
        fromService:
          type: redis
          name: gemini-chat-redis
          property: internalConnectionString

      # Gemini API (これらは手動で設定してください)
      - key: GEMINI_API_KEY
        sync: false  # 手動設定が必要

      - key: GOOGLE_API_VERSION
        value: v1beta

      - key: DEFAULT_GEMINI_MODEL
        value: gemini-2.5-flash

      - key: FALLBACK_GEMINI_MODEL
        value: gemini-2.5-pro

      - key: USE_MOCK_GEMINI
        value: false

      # Search API (これらは手動で設定してください)
      - key: SEARCH_PROVIDER
        value: google_cse

      - key: GOOGLE_API_KEY
        sync: false  # 手動設定が必要

      - key: GOOGLE_CSE_ID
        sync: false  # 手動設定が必要

  # Redis
  - type: redis
    name: gemini-chat-redis
    region: singapore  # Web/Worker/PostgreSQL と同じリージョン
    plan: free  # または starter
    ipAllowList: []  # 空 = すべてのIPを許可
    maxmemoryPolicy: allkeys-lru  # メモリ制限に達したとき、最後にアクセスされたキーを削除
