"""Add ResearchJob model for deep research feature

Revision ID: 89e7a3aca8eb
Revises: add_composite_indexes_20251013
Create Date: 2025-10-20 08:38:32.742710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e7a3aca8eb'
down_revision = 'add_composite_indexes_20251013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_conversation_user_pinned_id'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_conversation_id_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversation_id_id'), ['conversation_id', 'id'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_user_pinned_id'), ['user_id', 'is_pinned', 'id'], unique=False)
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
